### ISSUE TITLE
Q2.4.2a (id 127) is too vague

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#10]
Is it asking for years? Months? Days? Needs a help text or a better stating of the question.

**Comment by adilhasan** [comment]
It's years. I updated the question and added a help text.

**Comment by hmpf** [comment]
Did you update the question in the right plan? The id is always part of the url somewhere.

**Comment by adilhasan** [comment]
Hmm. Let me double check I did do that... You are right I edit the test one. I updated the correct one now.
