### ISSUE TITLE
Auditlog needed

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#11]
We need a log to see who has done what to what.

* Invitations sent, accepted, revoked (revoke=delete invitation, not rescind access)
* Plans created, locked, published
* Users created, probably

**Comment by hmpf** [comment]
This is now in review.

**Comment by adilhasan** [comment]
How do I access the audit long?

**Comment by hmpf** [comment]
On 02. aug. 2018 16:21, Adil Hasan wrote:
> How do I access the audit long?

It's below every plan for that plan. I haven't limited it to just the
latest just yet.

The complete log is accessible (read only) from the admin, see
"Eventlog". You can filter on target and object, and as soon as we have
something else than a user as an actor, on actor too. ("actor" can be
any table. So we could log a line whenever the eestore cache is
refreshed for instance, if it was done automatically.)

We could have a separate page per plan, with search-opportunities.
That's worth an issue.


-- 
HM

**Comment by adilhasan** [comment]
Ah ok it's called Events? Yes either limiting it or having it in a scrollable text box would be great. I think being able to filter the event log as an admin is fine. I think just being able to order by increasing or decreasing time for the audit log for the user is sufficient.

**Comment by hmpf** [comment]
Auditlog generatedd from 0.19.0 on. Not visible to endusers yet. Closing.
