### ISSUE TITLE
API accepts incorrect/unknown options without complaining

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#119]
If I supply an unknown or incorrect option to an API the option is silently ignored. For example:
curl "xxx/api/v1/plans/?aqwewqeqwe=2" seems to be accepted. Imho this should throw an error with option unknown otherwise it's a bit misleading and a source of witchcraft.

**Comment by hmpf** [comment]
It's how HTTP works everywhere else, though: Unknown keys, values in GET-queries are ignored. See what happens if you add garbage to the end of the github-url of this issue!
