### ISSUE TITLE
Q3.1a,b,c require some response

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#13]
Q3,1a,b,c are optional so it should be possible for the user to just skip the questions. I'm not sure how we can allow the user to do that. I think we may need a Q3.1 perhaps. I think it could be "Q3.1 Do you plan to manage your data yourself or do you intend to outsource the management to some infrastructure?" then we have 3.1a,b,c.

Thoughts?

**Comment by hmpf** [comment]
See #15

**Comment by hmpf** [comment]
So: what we need here is one branching obligatory question 3.1 with a yes/no: 
"will you be using infrastructure?"

Then what I want for 3.1.(a-c) is to combine them into a new "multiple-select with fill-in" question type. That takes two days.

You'd get:
list:
* international
* national
* other, elaborate below

textbox for other.

But what I think is that we need a list entry "institutional infrastructure" and maybe "infrastucture still to be determined". For instance. (The latter could go in the branching question and would be the same as "no".)

**Comment by adilhasan** [comment]
Yes this seems to be logical. I guess we can plan it for the update?
