### ISSUE TITLE
Section position collisions are silently ignored

### ISSUE THREAD

**Issue by vbhavdal** [hmpf/easydmp#134]
Make a template with sections in positions 1, 1 and 2. The duplicate for 1 is just silently not used, which makes the mistake hard to spot. 

Maybe fail hard on save() somewhere.

**Comment by hmpf** [comment]
We have a uniqe-constraint on `('template', 'super_section', 'position')` but since `super_section` can be SQL NULL, this only kicks in if `super_section` is set (since SQL NULL never compares equal to another SQL NULL).

**Comment by hmpf** [comment]
This was solved with ensuring that positions are unique per section, by preventing template designers from setting position directly. Closed by d8f1e36cb30f2dce98bd69d6353c0cb93d1ce92a
