### ISSUE TITLE
Q2.1.5a needs to be improved

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#14]
I'm putting here one of Damien's comments:

"""
Q2.1.5a What services will you use to provide searchable metadata?*
Proposed list of services (B2find & OpenAIRE) look a bit weird. We should assume that most people don’t know these services and without any concrete pointers to these services it is difficult for the lay person to tell anything. In particular, there is no indication of the work that is required to get your MD harvested by b2find. Is it automatic? As for OpenAIRE, the specific service should be mentioned (i.e. not just OpenAIRE). Finally we should allow people to choose “other” as an option, and tell us which service. Not just indicate them as “Not listed”.
"""

I don't think we can sort this out for Friday, but can work on it for an imminent release?

**Comment by hmpf** [comment]
No. Just as for Q3.1x #13 , this will need an extra question, which branches. Existing templates cannot be changed once they have been used. 

What we ought to have is a way to convert one plan to another, but for that the minimum support needed takes some additions to the cloning mechanism before we can even start on a converter.

**Comment by hmpf** [comment]
See #15

**Comment by hmpf** [comment]
We need to discuss how to give the end users more sufficient info about options. Might be smart to drag in an interaction designer on this. Should there be links on the question page (as part of the form widget?) Should there be a database/faq/wiki with more information, maybe linked from each question? If, so, who does the writing-job? When there's only two choices, like here, it's not so much, but we can't realistically think it will be possible for an eestore field with thousands of entries.

I don't know how to use b2find/openaire to get searchable metadata; who does and are they willing to write a paragraph or two for us?

**Comment by adilhasan** [comment]
I think I can write the text by searching the B2Find and openAIRE pages and then asking. I think that this should go into an FAQ and there should be a link to that question or section in the FAQ from the question.
