### ISSUE TITLE
Is it possible to query the questions belonging to a template?

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#154]
Hello, 
I would like to get the list of questions belonging to a given template. I thought that I could do:

curl "https://easydmp.sigma2.no/api/v1/questions/?template=63"

but, it seems to silently ignore the arguments. Is it possible to get the list of questions for a given template, or it's not something that's not supported. 
Many thanks, adil

**Comment by vbhavdal** [comment]
@adilhasan Looks like it needs to be `?section__template=63`, does that work? Using the Filters menu in the web UI yields that.

**Comment by adilhasan** [comment]
Sorry for getting back to you so late on this. No, it gives me the same results as 'template'.

**Comment by vbhavdal** [comment]
Maybe you missed the double underscores? This URL filters on template:

https://easydmp.sigma2.no/api/v1/questions/?section__template=63

**Comment by adilhasan** [comment]
Ah ha! Yes, you are right. It's double underscore and not single one. Thanks!
We can close this issue then
