### ISSUE TITLE
Batch export of plans to PDF

### ISSUE THREAD

**Issue by vbhavdal** [hmpf/easydmp#159]
RFK might need a common cache of their projects' DMPs (both EasyDMP and others) as PDF. To support this, consider implementing batched PDF export. Support project name as file name.

**Comment by hmpf** [comment]
By reusing the html template, if we have a sufficiently good html2pdf-converter, we can do with PDFs as we do with Section diagrams: create them on the fly, give them an endpoint/URL visible in the API/webUI just like "generated_html_url", and have RFK download them batchwise themselves.

**Comment by hmpf** [comment]
Can this issue be considered resolved by #164 or is something still missing?

**Comment by vbhavdal** [comment]
Fixed.
