### ISSUE TITLE
Q2.4.3 131 "Please input url(s) to the documentation" needs a better title

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#18]
Philipp C says: "What documentation?", which might mean that he doesn't see this page as connected to the previous page. Also, what do we do if there are no urls to the documentation?

**Comment by adilhasan** [comment]
I updated the text and put in the question label. Yes, we should support that case. I guess we cannot do it in this question as it would be a different type? Is it possible for there to be a 'no url field button that can lead to another question asking them to describe where the documentation is?

**Comment by hmpf** [comment]
That would also be another type. Might be better to have a textbox in that case, and save a "next"-click.

**Comment by adilhasan** [comment]
ok
