### ISSUE TITLE
Section.label cannot be changed from admin

### ISSUE THREAD

**Issue by frafra** [hmpf/easydmp#195]
I see sections' labels, but I cannot delete it from admin. Similar to #189.

https://github.com/hmpf/easydmp/blob/245cf8a1ae42095cd935c8b74c2e3e6742a4684a/src/easydmp/dmpt/models.py#L599-L602

https://github.com/hmpf/easydmp/blob/245cf8a1ae42095cd935c8b74c2e3e6742a4684a/src/easydmp/dmpt/models.py#L530

https://github.com/hmpf/easydmp/blob/815e4ca3715208092d2137a9e304ca1af999fa39/src/easydmp/dmpt/admin.py#L277-L289

**Comment by hmpf** [comment]
Closed by #196. Thx, @frafra!
