### ISSUE TITLE
Allow to hide "More information" field

### ISSUE THREAD

**Issue by frafra** [hmpf/easydmp#206]
Sometimes the "More information" field is just not needed. It would be nice to be able to just disable that for fields that requires a direct answer without any further comment.

**Comment by hmpf** [comment]
The easiest way to do this for any question is probably to turn the `has_notes` attribute into a field on the table. This should be a one day fix (+ tests) but probably not this week.

**Comment by hmpf** [comment]
Hm, if `has_notes` becomes a field, then we cannot easily override it automatically in the admin for `reason` and `shortfreetext`-types since the default for `has_notes` depends on `input_type`, and we do not know `input_type` until we save the first time.

**Comment by hmpf** [comment]
.. and no, changing the autogenerated admin to such a degree with javascript that it changes the rest of the form depending on what is chosen for `input_type` is right out. That way lies madness.

**Comment by hmpf** [comment]
Found a way. Works in 1.13, closing issue.
