### ISSUE TITLE
Template revision/cloning/JSON import

### ISSUE THREAD

**Issue by frafra** [hmpf/easydmp#208]
Given that it does not seem a good idea to change if there are DMP connected to that (see #207), it would be nice to be able to create a new template based on a previous one (like a new revision).
Current templates can be exported as JSON file, but there is no import function for those files in the admin.

**Comment by vbhavdal** [comment]
@frafra There is a gray import button top right, that can be used for this, can't it?

**Comment by frafra** [comment]
@vbhavdal Sorry, I do not see it. I am using the instance running on easydmp.sigma2.no. I guess it could be a permission issue?

**Comment by hmpf** [comment]
There is a way to both clone an entire existing template, and to import an exported template, via the admin. It makes sense that this should be possible to those who are in the "Template Designer" group, as I think you are, @frafra. It shouldn't be too much work to add the necessary permissions. Those that only have access to editing a *specific* template will not be allowed this though.

**Comment by hmpf** [comment]
There is a way to both clone an entire existing template, and to import an exported template, via the admin. It makes sense that this should be possible to those who are in the "Template Designer" group, as I think you are, @frafra. It shouldn't be too much work to add the necessary permissions. Those that only have access to editing a *specific* template will not be allowed this though.

**Comment by hmpf** [comment]
I realized: Django 2.1 added the support for "view"-permissions. It might be possible to change the admin so that published templates (with all its dependents) are read-only for everyone, including super-users. Then imported templates would be editable depending on whether the original was published or not.
