### ISSUE TITLE
Comment section does not support HTML

### ISSUE THREAD

**Issue by frafra** [hmpf/easydmp#209]
The "Comment" section does not support HTML while "Help text" does. Is there any rationale behind that? Otherwise, I would propose to allow HTML (for rich text and links) in all these fields.

**Comment by hmpf** [comment]
Rationale: the Comment-section has been used very little and we've never gotten any feedback on needs for it :)

**Comment by hmpf** [comment]
Strictly speaking, you can _store_ HTML in the field already, it's just that it is escaped when users fill out plans.

**Comment by frafra** [comment]
No problem with that :) Thanks.

**Comment by hmpf** [comment]
Extremely easy to fix though, see PR.

One thing that won't ever be supported is users entering HTML when filling out a plan, for security reasons.

**Comment by vbhavdal** [comment]
Markdown is probably easy to add though.

**Comment by hmpf** [comment]
Which markdown? :) And how do you prevent inline HTML? Markdown allows inline HTML.
