### ISSUE TITLE
UI to show what is validated is needed

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#22]
See issue #20

**Comment by adilhasan** [comment]
I think that the service can only perform some rudimentary validation of the plan. We could have some checkboxes that the user needs to check to confirm the plan has been checked (validated) by the PI and others in the project? I think we need to make sure we don't confuse with reviewing a plan which is the purpose of the funding agency.

**Comment by hmpf** [comment]
On 2018-06-06 19:49, Adil Hasan wrote:
> I think that the service can only perform some rudimentary validation of
> the plan. We could have some checkboxes that the user needs to check to
> confirm the plan has been checked (validated) by the PI and others in
> the project?

I think you interpret "validation" different than me. What I meant is
"check that all questions that need be answered have been answered".

What you're talking about is new feature country and not for 1.0.

**Comment by adilhasan** [comment]
Perhaps we have:
validation - the plan is checked programmatically. As far as the program is concerned it's complete.
review - the plan is reviewed by the plan authors (including the research office/library)
assessment - the plan is assessed by the funding agency and either approved or declined.

I think for review we can have a checkbox so part of the validation is has this plan been reviewed? It would get around some more complicated workflows for now. What do you think?

**Comment by hmpf** [comment]
Ugly hack is in review.

**Comment by hmpf** [comment]
Ugly hack deployed.
