### ISSUE TITLE
Plan Overview at the beginning

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#249]
Oystein would like to see an overview or summary of the plan so he knows what questions there are and the sections and he can then pick the ones he wants to fill in at that time. He wants the overview right at the beginning. So, the researcher fills in the plan title and then is immediately brought to the overview/summary.

I thought that this may be tricky to do in the case a plan has branches, but I guess one could give the overview according the main branch and warn that this is only an estimate. Maybe questions that have a branch could be marked with a star or something.

**Comment by hmpf** [comment]
See also #202

**Comment by hmpf** [comment]
Included in 42317d9cbf63bede2fac814339c1be101101fcb6
