### ISSUE TITLE
GDPR: if we end up with type "consent", what to do with added_by, modified_by etc?

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#27]
The `*_by`-fields on a plan are linked directly to a person. If that person deletes his user, unless we change things, any plan with that user in a `*_by`-field will be deleted. This might be fine for unpublished plans, but not quite so for doi-ed, published plans and certainly not for plans with more than one editor.

The easiest fix to preserve plans is to set the `*_by`-fields to empty. We could also remove all `*_by`-fields and use a logging-mechanism instead. But you're not supposed to ever change a log.

**Comment by adilhasan** [comment]
I think we need to run this by the Research Council as I am not sure of the person's name would appear in the document. In that case if the document is published it's a bit like a published paper and it's not possible to remove the users name from the document. But, if it's metadata and not in the plan I guess it can be deleted.

**Comment by hmpf** [comment]
Stale. 0.19.0 generates an auditlog, but it is not yet visible to non-superuser users.
