### ISSUE TITLE
Contributor email same as owner email

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#28]
If I own a plan and try and share it with myself with the same email address the service doesn't detect that I am trying to do this. Should we prevent a user from trying to share with herself? Perhaps detect and say you already own the plan or this plan is already shared with this user?

**Comment by hmpf** [comment]
The latter, I think.

Though, there's no easy way to change an existing viewer into an editor (and vice versa) today.

I've made issue #29 for this. It'll need a new TODO.
