### ISSUE TITLE
Can click comment without saving question

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#30]
In the review version if I click on 'comment' I am presented with the text field, but my answers to the question are not saved. Is it possible to somehow save the question?

**Comment by hmpf** [comment]
Not without javascript, as it is two different html `<form>`s.

If the comment-system functioned like a popup, then you would probably realize that it doesn't make sense to save the answer when you make a comment. Anyway, the comment is connected to a specific question (and the current answer, sorta), not a specific answer, and changing that would be tricky. For instance, if we changed the answer, what should happen to the comments to the previous answers? If they are to be kept, we would need full versioning of answers, and that is one hefty feature request with major repercussions.

Note that not even google docs solve this, you can change the line a comment hangs on, but even if the comment is no longer valid, it is still there.

This is not a bug, but is as designed. This is also one reason why we need some UI-specialists to have a look. I'm removing the tag. (Whenever it is tempting to write "Is it possible to do this instead", it is probably not a bug, but a feature request/enhancement.)

This is not connected to H2020. Removing that tag also.
