### ISSUE TITLE
Have an "accesses/share"-pane for administering users

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#31]
A plan (on the review-system) currently has two types of users:

* viewers
* editors

Being an editor implies also being a viewer.

There's no easy way to convert between the two. All changes to user-access to a plan need to be collected in one place. That is:

* invitations, and everything connected to that
* changing the status of an existing user, including removing that user. But who gets to remove users?
* user should be able to lower or remove their own access to a plan, so that an editor can change themself into a viewer instead, or leave the plan altogether.

**Comment by adilhasan** [comment]
regarding removing users I think only the owner of the plan should be able to remove users. That means that only the owner of the plan can create users. It should be possible for a person to transfer ownership to another user. 

We would need to think about 'orphaned plans' where the user has left the organisation and another user needs to take over. I think at that point the administrator of the service should be able to transfer ownership.

**Comment by hmpf** [comment]
I'm working on this now. Viewers get a mostly read-only view: they can remove themselves from the plan on their own.

Editors, any editor, can change the accesses of anyone else, but not make anyone but themselves leave the project.

Invites will also happen from this page, that is: links to the "send invitation"-pages will be included. After sending an invitation, the sender will be sent back to this page.

**Comment by hmpf** [comment]
First draft done and ready for review.

**Comment by hmpf** [comment]
Changes deployed.
