### ISSUE TITLE
Section Introduction not appearing in multiple questions per page plan

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#50]
On the Paas I cannot see the section introduction before each section for the NFR template.

**Comment by hmpf** [comment]
Do you mean when updating a template? Click the wedge pointing downards at the right. Should it be like this or should we always show the introduction? This was a USIT preference if you recall.

**Comment by hmpf** [comment]
If you mean in the plan summary, it pops up with that wedge at the right again.

**Comment by adilhasan** [comment]
No, not when updating a template. When I am creating a plan and I am in a section the introduction text for the section isn't there and there's no wedge. I renamed the NFR template to SE (Science Europe template).

**Comment by hmpf** [comment]
Maybe a browser thing? The wedge is controlled by javascript. I'll upload a screenshot from my Firefox.

**Comment by adilhasan** [comment]
I was using firefox too, but maybe there is something with the version I am using.

**Comment by hmpf** [comment]
Ok now, closing.
