### ISSUE TITLE
Linear template doesn't save when clicking 'next'

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#52]
For the H2020 linear template and the NIBIO template which have more than one question on a page when I fill in plan details and click 'next' the details are not saved. If I then click on the plan summary I cannot see the information that I filled in.

**Comment by hmpf** [comment]
Is this iin production or somewhere else?

**Comment by adilhasan** [comment]
it's in production and I noticed it in the nibio template.

**Comment by hmpf** [comment]
Save and next works weirdly. Save saves thn goes next. Next just goes next it seems.

**Comment by hmpf** [comment]
Save should save then stay on the page. Next should save then go next.

**Comment by hmpf** [comment]
Fix will be in the next release.
