### ISSUE TITLE
Pages with optional and mandatory fields

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#53]
I created a linear template and I had on one page one question that was optional. When I started to fill in the plan and then clicked on 'next' to go to the page with the optional question I got a 'page not found' error. I then changed the question to mandatory and was able to go to the next page.

**Comment by hmpf** [comment]
Where is the template?

**Comment by adilhasan** [comment]
yes this was the nibio template. I have since change the question to mandatory and it's fine.

**Comment by hmpf** [comment]
Production `Question`s have the field "obligatory". For a linear template, all fields are obligatory. The optional code isn't in yet. "obligatory" here means "must be seen, visited, considered". A question only reachable by a branch is not obligatory.

How would you recommend we document this? (In docs/, for template designers.)

**Comment by adilhasan** [comment]
Yes I think in docs for template designers.

**Comment by hmpf** [comment]
See ``docs/templates/creating_templates.rst``.
