### ISSUE TITLE
Import/export of templates and plans

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#55]
Importing a plan depends on the template already being in, so import/export of templates take priority.

The main problem is the use of autogenerated primary keys.

Ideas:

-  Add natural keys to everything in `dmpt` so templates can be exported.

   Turns out, CannedAnswer/ExplicitBranch is a little unspecified so nothing added for them.

- [x] Export of templates

  - [x] Serializer for exports
  - [x] API/link for exports
  - [x] CLI
  - [x] Maybe admin?

- [ ] Import of templates, in order of dependencies:

  - [x]   1. A function/method for import
  - [x]   2. A mangement command to use from the CLI
  - [ ]   3. Admin interface
  - [ ]   3. API interface
  - [ ]   4. Frontend interface

- [ ] Plan import/export: map question id's to natural keys.

Natural keys:

Originating site should be part of it. URIs?

**Comment by hmpf** [comment]
. but how to export flow? Probably best to export the calculated, complete, explicit flow, and avoid the FSAs altogether.

**Comment by adilhasan** [comment]
I think the issue can be that the questions may not make sense without the flow. Would it be possible to export the flow separately? Also, if a user exports a template and imports into their site and then modifies the template would it be possible to handle that? What about the case where a user exports a template from easyDMP-A and imports into easyDMP-B and then modifies the template in easyDMP-B and then exports again from easyDMP-B and imports into easyDMP-A. Would that be possible?

**Comment by adilhasan** [comment]
I think exporting a template may need a version number (of some kind - possibly autogenerated by easydmp).

**Comment by hmpf** [comment]
> I think exporting a template may need a version number (of some kind - possibly autogenerated by easydmp).

All templates already have a version number.

**Comment by hmpf** [comment]
Natural keys: site (domainname), version if exists, slug of title, pk. Expressable as an URI.

**Comment by adilhasan** [comment]
Ok so that means somehow to prevent clashing root names?

**Comment by hmpf** [comment]
Yeah this is where the domain name comes in. It moves with the template. New version on a new server should use the domain name of the new server though.

**Comment by adilhasan** [comment]
How would one avoid a person choosing the same site name as an existing one?

**Comment by hmpf** [comment]
Because site==domain. They don't get to choose.

**Comment by hmpf** [comment]
It'll be a field on the template and so can be changed by a superuser, but everywhere else it'll be read only. For published templates it is easy. You can only import once, because since the template cannot change, importing the same one twice is a waste of electrons. For unfinished templates; maybe replacing the previously imported one or increasing the version number until (title, version) is unique again.

**Comment by hmpf** [comment]
I've been thinking some more on this. When moving the plan, it might be easier to have a stored mapping on the receiver between the two templates that just maps question id to question id.

```
class TemplateMap(Model):
    their_id ..
    our_id ..
    ..

class QuestionMap(Model):
    their_id ..
    our_id ..
    ..
```

Natural keys everywhere is still wise though, increases our backup/restore options.

**Comment by hmpf** [comment]
Import/export of plans moved to #240
