### ISSUE TITLE
publishing a plan

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#62]
Just a quick question. Are the linear templates meant to have a publish button? I think that it is fine that they do not as we cannot issue DOI for the plans and we are not certain when a plan should be published.

**Comment by hmpf** [comment]
All have publish buttons. "Publish" right now means "make public and unchangeable", same as with templates. It won't be visible many places (like in the API) unless it is "published".

**Comment by adilhasan** [comment]
We don't issue a persistent identifier, but there is a URL that is publicly accessible? I'm having problems with my plan getting the publish flag to appear. I'm not too sure what I'm missing.

**Comment by hmpf** [comment]
I think there's a bug in the chcek code. I'll lock into it. When every obligatory but not optional question has been answered and "Check" has been clicked, there should be a checkmark in a box next to every section title and the plan title, and "Check" changes to "Publish".

**Comment by hmpf** [comment]
Check has been fixed, Publish has been replaced with Lock since nobody can agree on a publish-process yet.
