### ISSUE TITLE
what should check do?

### ISSUE THREAD

**Issue by adilhasan** [hmpf/easydmp#63]
For a linear template, what should the check button do? I don't see any difference in the plan.

**Comment by hmpf** [comment]
Just as with branching plans, it runs through all questions and sets whether the sections are valid and finally if the plan itself is valid. It might be (I have to check) that this is also set when changing a question. With branching it (IIRC) also checks that it branches correctly, that is: all section's branches correspond to a possible branching route for that section.

**Comment by adilhasan** [comment]
Does it flag where there is something missing? In the linear SE template I run Check, but it's not clear to me what the result is. I suspect I'm doing something wrong. I shared the plan with you.

**Comment by hmpf** [comment]
There was a bug. It will be fixed in the next release.

**Comment by hmpf** [comment]
It does not tell you where something is missing, but each ok section also gets a checkmark, so sectiosn without a checkmark aren't ok.

If there should be some other way of marking what is missing, that's a feature request.
