### ISSUE TITLE
Support optional sections

### ISSUE THREAD

**Issue by hmpf** [hmpf/easydmp#88]
RDA DMP CS has sections that

1. may occur once (0..1)
2. must occur once (1..1)
3. may occur more than once (0..n)
4. must occur at least once but may occur more than once (1..n)

EasyDMP currently only supports case 2 above. A way is needed to support cases 1 and 3.

**Comment by hmpf** [comment]
The "more than once" bits of case 3 and 4 are covered by #81.

**Comment by hmpf** [comment]
An optional Section can be done by having an "optional" flag on the Section-object and an "optional_canned_text" (default: empty) to put in the `generated_plan_html`. Auto-generate a Yes/No as an implicit first question. Choosing "Yes" starts the section, "No" hops to the next section. *Maybe* there also should be a way to control what the question asking if the section is needed looks like: a question introduction, a text for the yes-answer and a text for the no-answer, with canned texts for the `generated_plan_html`?

Good example: q2.1.1 of "Horizon 2020", which could be its own section.

**Comment by adilhasan** [comment]
I think that indeed it's a question introduction and it can have a canned response. Makes sense.

**Comment by hmpf** [comment]
There shouldn't be any need to change how answers are stored for optional questions, just when validating.

* An optional section may be valid or invalid
* If invalid, the plan is invalid
* If skipped, validiation-status should not be checked.

**Comment by hmpf** [comment]
This will affect the views NewQuestionView (poorly named) and UpdateLinearSectionView. The former handles branching sections and goes question by question. The latter handles linear section and goes section by section. It is a bit of a mess, just look at `get_success_url()` in them.

This optionality needs to be checked *before* starting on the first question (NewQuestionView) or first section (UpdateLinearSectionView), and *inbetween* going from a section's last question (NewQuestionView) and between sections (UpdateLinearSectionView). Maybe the choice of which view to go to next should be moved from NewQuestionView/UpdateLinearSectionView to this optionality-checker view.

**Comment by vbhavdal** [comment]
@hmpf Do you think abusing position -1 like this will work? https://github.com/hmpf/easydmp/pull/101

**Comment by hmpf** [comment]
Position '0' I think or we need to change the type of `Question.position`. What then would position '-2' mean?

Doing it ithis way: This answer will be stored together with all the other answers, and we might not really need any changes to the Section-model attributes. Though I'd still recommend an `optional`-toggle so that we can check if the magic question exists. The magic question would need to check that its position is '0', and that there may be only one in a section. We can't really do this with sql because proxy models. The magic question is a subtype of a BooleanQuestion, really.

**Comment by hmpf** [comment]
We're gonna need `Section.optional` regardless, best way for a view to find out what to do.

**Comment by hmpf** [comment]
.. thinking some more, BooleanQuestion should on save check that it has both a Yes and a No canned answer. I don't think it does this today.

**Comment by hmpf** [comment]
Closed by #121.
